let suggestions = [
    "Professional English",
    "Engineering Drawing",
    "Programming for Problem Solving",
    "Chemistry",
    "Physics",
    "Electrical",
    "Physio",
    "Bio Chemistry",
    "Mathematics",
    "Biology",
    "Computer Applications",
    "Enviromental",
    "Pharmalogy",
    "Micro-Biology",
    "Pharma  engineering",
    "Organic Chemistry",
    "Phytochem",
    "Medicinal Chemistry",
    "Industrial Pharmalogy",
    "Pharmalogy Practice",
    "Cell and pharma",
    "Project ",
    "Cosmetic",
    "Bio technology",
    "Herbal Science",
    "Experimental Pharma",
    "DBMS",
    "Data Base Management System",
    "compiler Design",
    "Data Structures",
    "C++",
    "Python",
    "Java",
    " Electronics Devies",
    "Digital System Design ",
    "Digital Signal Processing",
    "Optical Communication",
    "Antenna And Wave Propogation",
    "Thermodynamics",
    "Fluid Mechenics",
    "Production Technology",
    "Machine drawing",
    "Heat Transfer",
    "Numerical Methods",
    " ",
    "Digital System Design ",
    "Digital Signal Processing",
    "Optical Communication",
    "Antenna And Wave Propogation",
];